### ISSUE TITLE
Prior versions?

### ISSUE THREAD

**Issue by joshbmarshall** [ordinary9843/ghostscript#1]
Hi just wondering what happened to prior versions? The new package is incompatible with my installation and I can't do anything with composer because it can't find the prior versions of the package in packagist.

**Comment by ordinary9843** [comment]
Please provide your PHP version, I will try fix & release new version.

**Comment by joshbmarshall** [comment]
Running PHP 8.2 here - but the issue is that in my composer file I have:

     "ordinary9843/ghostscript": "^1.2",

And now only v1.0.0 is available. So it's not letting me do a composer upgrade

I haven't attempted removing and adding again but I use the constant: `\Ordinary9843\Ghostscript::STABLE_VERSION` and I believe this has been moved.

**Comment by joshbmarshall** [comment]
Is not an urgent thing - I've changed my system to use the new version, but it just thinks I'm downgrading. You may get others who also have problems that the new version was created with a lower version number and incompatible.

**Comment by ordinary9843** [comment]
Initially, I thought this package might only be used by me personally, but it turns out there are other users. I will handle it as soon as possible. Sorry for any inconvenience!

**Comment by joshbmarshall** [comment]
No problems. Thanks for writing the package! My apologies if I came across the wrong way. You could see if anyone else has issues before proceeding.

That said, packagist says your package has been downloaded 11000+ times, so it is used by quite a few people :)

**Comment by ordinary9843** [comment]
I fixed this issue and released a new version. I have also adjusted support for a broader range of PHP versions (7.1 - 8.x). If you have any questions or suggestions, I am more than happy to consider them. Thank you for your feedback! Hope it helps you!
